# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 332dc03433d7f9586b51a4a8c2fe7c2625add9ddf9d98b8386142728b718e49d35b9024476da6ab456f77683b178f932fa3c3b1436df7ddae7122eb3cc928fef

test:
  secret_key_base: d0cd3b5ee4a5eb68810471fa28d959b2c5c3e11b59d8f0d3ec3d4f0420c086e624947b9041ea68abc6a39a04619b116ec74398a5c2c2019cf5e39f9ed2d4a4cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
